# Generated by Django 6.0.6 on 2026-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrintOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razorpay_order_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("firebase_file_path", models.CharField(max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                ("page_count", models.IntegerField(default=1)),
                ("color_mode", models.CharField(max_length=50)),
                ("copies", models.IntegerField(default=1)),
                ("binding_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
