# Generated by Django 6.0.6 on 2026-06-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_print", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="printorder",
            old_name="page_count",
            new_name="claimed_pages",
        ),
        migrations.AddField(
            model_name="printorder",
            name="actual_pages",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="printorder",
            name="price_calculated",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
