# Generated by Django 6.0.5 on 2026-06-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_print", "0002_rename_page_count_printorder_claimed_pages_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrintOrder",
        ),
    ]
